### ISSUE TITLE
Have the builder take a btrfs snapshot after each stage completes

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#40]
The reason for this would be to support resuming from an arbitrary point in the build process, even after other steps have finished.

**Comment by perkinslr** [comment]
Since we use the native filesystem for building, this would require the host system be using btrfs.  It's a good idea, but should have an environment variable to toggle it on and off (I'm fine defaulting to on, but not picky either way).  Also wouldn't be amiss to have it call a script to do the snapshotting, in case we decide we need to handle other filesystems or snapshot methods later.

**Comment by jonesmz** [comment]
>  It's a good idea, but should have an environment variable to toggle it on and off  

Of course

>  Also wouldn't be amiss to have it call a script to do the snapshotting, in case we decide we need to handle other filesystems or snapshot methods later.

Agreed

**Comment by perkinslr** [comment]
Use `export BTRFS_SNAPSHOTS=/path/to/hold/snapshots` to enable this.
