### ISSUE TITLE
mountimage script pulls path from config.py, but unpackstage4 doesn't

### ISSUE THREAD

**Issue by jonesmz** [GenPi64/Build.Dist#83]

**Comment by perkinslr** [comment]
I'm not sure what the issue here is.  The image is always mounted on `${PROJECT_DIR}/image`, and the stage4 file name is always `latest-${PROJECT}.tar.zst`.  The image *file* name is read from the config, but the unpack step doesn't need to know what the underlying image file is called, as it's already mounted.
